// examples/preact-compat/src/examples/HFragmentDemo.tsx
import { createElement, Fragment, h } from "preact"
import { useState } from "preact/hooks"
import Demo from "./Demo"

export default function HFragmentDemo() {
  const [items, setItems] = useState(["one", "two", "three"])

  return (
    <Demo
      title="h / createElement / Fragment"
      apis="h, createElement, Fragment"
      code={`// h() — hyperscript
h("p", null, "Hello from h()")

// createElement — alias for h
createElement("p", null, "Same thing")

// Fragment — no wrapper node
h(Fragment, null, h("span", null, "A"), h("span", null, "B"))`}
    >
      {h("p", null, "Created with ", h("strong", null, "h()"))}
      {createElement("p", null, "Created with ", createElement("strong", null, "createElement()"))}
      {h(
        Fragment,
        null,
        h("p", { class: "muted" }, "Fragment child 1"),
        h("p", { class: "muted" }, "Fragment child 2"),
      )}
      <p>
        Items: <strong>{items.join(", ")}</strong>
      </p>
      <button
        type="button"
        onClick={() => setItems((prev) => [...prev, `item-${prev.length + 1}`])}
      >
        Add item
      </button>
    </Demo>
  )
}

// examples/vue-compat/src/examples/HFragmentDemo.tsx
import { Fragment, h, ref } from "vue";
import Demo from "./Demo";

export default function HFragmentDemo() {
  const items = ref(["one", "two", "three"]);

  return (
    <Demo
      title="h() & Fragment"
      apis="h, Fragment"
      code={`// h() — manual VNode creation
h("p", null, "Created with h()")

// Fragment — group without wrapper
h(Fragment, null,
  h("span", null, "A"),
  h("span", null, "B"),
)`}
    >
      {h("p", null, "This paragraph was created with ", h("strong", null, "h()"))}
      {h(
        Fragment,
        null,
        h("p", { class: "muted" }, "Fragment child 1"),
        h("p", { class: "muted" }, "Fragment child 2"),
      )}
      <p>
        Items: <strong>{items.value.join(", ")}</strong>
      </p>
      <button
        type="button"
        onClick={() => (items.value = [...items.value, `item-${items.value.length + 1}`])}
      >
        Add item
      </button>
    </Demo>
  );
}
