// packages/react-compat/src/index.ts
/**
 * @pyreon/react-compat
 *
 * React-compatible hook API that runs on Pyreon's reactive engine.
 *
 * Allows you to write familiar React-style code while getting Pyreon's
 * fine-grained reactivity, built-in router/store, and superior performance.
 *
 * DIFFERENCES FROM REACT:
 *  - No hooks rules: call these anywhere in a component, in loops, conditions, etc.
 *  - useEffect deps array is IGNORED — Pyreon tracks dependencies automatically.
 *  - useCallback/memo are identity functions — no re-renders means no stale closures.
 *  - Components run ONCE (setup), not on every render.
 *
 * USAGE:
 *   Replace `import { useState, useEffect } from "react"` with
 *             `import { useState, useEffect } from "@pyreon/react-compat"`
 *   Replace `import { createRoot } from "react-dom/client"` with
 *             `import { createRoot } from "@pyreon/react-compat/dom"`
 */

// Re-export Pyreon's JSX runtime so JSX transforms work the same way
export { h as createElement, Fragment } from "@pyreon/core"
export { h } from "@pyreon/core"
export type { VNode as ReactNode, VNodeChild, Props } from "@pyreon/core"

// Lifecycle
export { onMount as useLayoutEffect } from "@pyreon/core"

import {
  signal,
  computed,
  effect,
  batch,
  createSelector,
  runUntracked,
  getCurrentScope,
} from "@pyreon/reactivity"
import {
  onMount,
  onUnmount,
  onUpdate,
  onErrorCaptured,
  createRef,
  createContext,
  useContext,
  Portal,
  Suspense,
  ErrorBoundary,
} from "@pyreon/core"
import type { VNodeChild, CleanupFn, Props, ComponentFn, LazyComponent } from "@pyreon/core"

// ─── State ────────────────────────────────────────────────────────────────────

/**
 * Drop-in for React's `useState`.
 * Returns `[getter, setter]` — call `getter()` to read, `setter(v)` to write.
 *
 * Unlike React: the getter is a signal, so any component or effect that reads
 * it will re-run automatically. No dep arrays needed.
 */
export function useState<T>(initial: T | (() => T)): [() => T, (v: T | ((prev: T) => T)) => void] {
  const s = signal<T>(typeof initial === "function" ? (initial as () => T)() : initial)
  const setter = (v: T | ((prev: T) => T)) => {
    if (typeof v === "function") s.update(v as (prev: T) => T)
    else s.set(v)
  }
  return [s, setter]
}

// ─── Reducer ─────────────────────────────────────────────────────────────────

/**
 * Drop-in for React's `useReducer`.
 */
export function useReducer<S, A>(
  reducer: (state: S, action: A) => S,
  initial: S | (() => S),
): [() => S, (action: A) => void] {
  const s = signal<S>(typeof initial === "function" ? (initial as () => S)() : initial)
  const dispatch = (action: A) => s.update((prev) => reducer(prev, action))
  return [s, dispatch]
}

// ─── Effects ─────────────────────────────────────────────────────────────────

/**
 * Drop-in for React's `useEffect`.
 *
 * The `deps` array is IGNORED — Pyreon tracks reactive dependencies automatically.
 * If `deps` is `[]` (mount-only), wrap the body in `runUntracked(() => ...)`.
 *
 * Returns a cleanup the same way React does (return a function from `fn`).
 */
export function useEffect(fn: () => CleanupFn | void, deps?: unknown[]): void {
  if (deps !== undefined && deps.length === 0) {
    // [] means "run once on mount" — use onMount instead of a tracking effect
    onMount((): undefined => {
      const cleanup = runUntracked(fn)
      if (typeof cleanup === "function") onUnmount(cleanup)
    })
  } else {
    // No deps or non-empty deps: run reactively (Pyreon auto-tracks)
    const e = effect(() => {
      const cleanup = fn()
      if (typeof cleanup === "function") return cleanup
    })
    onUnmount(() => e.dispose())
  }
}

/**
 * Drop-in for React's `useLayoutEffect`.
 * In Pyreon there is no paint distinction — maps to `onMount` (same as useEffect).
 */
export { useEffect as useLayoutEffect_ }

// ─── Memoization ─────────────────────────────────────────────────────────────

/**
 * Drop-in for React's `useMemo`.
 * The `deps` array is IGNORED — Pyreon's `computed` tracks dependencies automatically.
 * Returns a getter: call `value()` to read the memoized result.
 */
export function useMemo<T>(fn: () => T, _deps?: unknown[]): () => T {
  return computed(fn)
}

/**
 * Drop-in for React's `useCallback`.
 * In Pyreon, components run once so callbacks are never recreated — returns `fn` as-is.
 */
export function useCallback<T extends (...args: unknown[]) => unknown>(fn: T, _deps?: unknown[]): T {
  return fn
}

// ─── Refs ─────────────────────────────────────────────────────────────────────

/**
 * Drop-in for React's `useRef`.
 * Returns `{ current: T }` — same shape as React's ref object.
 */
export function useRef<T>(initial?: T): { current: T | null } {
  const ref = createRef<T>()
  if (initial !== undefined) ref.current = initial as T
  return ref
}

// ─── Context ─────────────────────────────────────────────────────────────────

/**
 * Drop-in for React's `createContext` + `useContext`.
 * Usage mirrors React: `const Ctx = createContext(defaultValue)`.
 */
export { createContext, useContext }

// ─── ID ───────────────────────────────────────────────────────────────────────

/**
 * Drop-in for React's `useId` — returns a stable unique string per component instance.
 *
 * Uses the component's effectScope as the key so the counter starts at 0 for every
 * component on both server and client — IDs are deterministic and hydration-safe.
 */
const _idCounters = new WeakMap<object, number>()

export function useId(): string {
  const scope = getCurrentScope()
  if (!scope) return `:r${Math.random().toString(36).slice(2, 9)}:`
  const count = _idCounters.get(scope) ?? 0
  _idCounters.set(scope, count + 1)
  return `:r${count.toString(36)}:`
}

// ─── Optimization ─────────────────────────────────────────────────────────────

/**
 * Drop-in for React's `memo` — wraps a component.
 * In Pyreon, components run once (no re-renders), so memoization is a no-op.
 * Kept for API compatibility when migrating React code.
 */
export function memo<P extends Record<string, unknown>>(
  component: (props: P) => VNodeChild,
): (props: P) => VNodeChild {
  return component
}

/**
 * Drop-in for React's `useTransition` — no-op in Pyreon (no concurrent mode).
 * Returns `[false, (fn) => fn()]` to keep code runnable without changes.
 */
export function useTransition(): [boolean, (fn: () => void) => void] {
  return [false, (fn) => fn()]
}

/**
 * Drop-in for React's `useDeferredValue` — returns the value as-is in Pyreon.
 */
export function useDeferredValue<T>(value: T): T {
  return value
}

// ─── Batching ─────────────────────────────────────────────────────────────────

/**
 * Drop-in for React's `unstable_batchedUpdates` / React 18's automatic batching.
 * Pyreon's `batch()` does the same thing.
 */
export { batch }

// ─── Error boundaries ─────────────────────────────────────────────────────────

/**
 * Drop-in for React's error boundary pattern.
 * Return `true` from `handler` to prevent error propagation (like `componentDidCatch`).
 */
export { onErrorCaptured as useErrorBoundary }

// ─── Portals ─────────────────────────────────────────────────────────────────

/**
 * Drop-in for React's `createPortal(children, target)`.
 */
export function createPortal(children: VNodeChild, target: Element): VNodeChild {
  return Portal({ target, children })
}

// ─── Imperative handle ────────────────────────────────────────────────────────

/**
 * Drop-in for React's `useImperativeHandle`.
 * In Pyreon, expose methods via a ref prop directly — this is a compatibility shim.
 */
export function useImperativeHandle<T>(
  ref: { current: T | null } | null | undefined,
  init: () => T,
  _deps?: unknown[],
): void {
  onMount((): undefined => {
    if (ref) ref.current = init()
    onUnmount(() => { if (ref) ref.current = null })
  })
}

// ─── Selector ─────────────────────────────────────────────────────────────────

/**
 * Pyreon-specific: O(1) equality selector (no React equivalent).
 * Useful for large lists where only the selected item should re-render.
 * @see createSelector in @pyreon/reactivity
 */
export { createSelector }

// ─── onUpdate ─────────────────────────────────────────────────────────────────

/** Pyreon-specific lifecycle hook — runs after each reactive update. */
export { onMount, onUnmount, onUpdate }

// ─── Suspense / lazy ──────────────────────────────────────────────────────────

/**
 * Drop-in for React's `lazy()`.
 * Wraps a dynamic import — the returned component renders null until the module
 * resolves. Pair with `<Suspense>` to show a fallback during loading.
 *
 * Usage:
 *   const MyPage = lazy(() => import("./MyPage"))
 *   <Suspense fallback={<Spinner />}><MyPage /></Suspense>
 */
export function lazy<P extends Props>(
  load: () => Promise<{ default: ComponentFn<P> }>,
): LazyComponent<P> {
  const loaded = signal<ComponentFn<P> | null>(null)
  load().then((m) => loaded.set(m.default))

  const wrapper = (props: P): ReturnType<ComponentFn<P>> => {
    const comp = loaded()
    return comp ? comp(props) : null
  }
  wrapper.__loading = () => loaded() === null
  return wrapper as LazyComponent<P>
}

/**
 * Drop-in for React's `<Suspense>`.
 * Shows `fallback` while a `lazy()` child is still loading.
 */
export { Suspense, ErrorBoundary }

// packages/solid-compat/src/index.ts
/**
 * @pyreon/solid-compat
 *
 * Fully SolidJS-compatible API powered by Pyreon's reactive engine.
 *
 * Components re-render on state change via the compat JSX runtime wrapper.
 * Signals use Pyreon's native signal system internally (enabling auto-tracking
 * for createEffect/createMemo), while the component body runs inside
 * `runUntracked` to prevent signal reads from being tracked by the reactive
 * accessor. Only the version signal triggers re-renders.
 *
 * USAGE:
 *   import { createSignal, createEffect } from "solid-js"  // aliased by vite plugin
 */

import type { ComponentFn, LazyComponent, Props, VNodeChild } from "@pyreon/core"
import {
  ErrorBoundary,
  For,
  Match,
  createContext as pyreonCreateContext,
  onMount as pyreonOnMount,
  onUnmount as pyreonOnUnmount,
  useContext as pyreonUseContext,
  Show,
  Suspense,
  Switch,
} from "@pyreon/core"
import {
  type EffectScope,
  effectScope,
  getCurrentScope,
  batch as pyreonBatch,
  computed as pyreonComputed,
  createSelector as pyreonCreateSelector,
  effect as pyreonEffect,
  signal as pyreonSignal,
  runUntracked,
  setCurrentScope,
} from "@pyreon/reactivity"
import { getCurrentCtx, getHookIndex } from "./jsx-runtime"

// ─── createSignal ────────────────────────────────────────────────────────────

export type SignalGetter<T> = () => T
export type SignalSetter<T> = (v: T | ((prev: T) => T)) => void

export function createSignal<T>(initialValue: T): [SignalGetter<T>, SignalSetter<T>] {
  const ctx = getCurrentCtx()
  if (ctx) {
    const idx = getHookIndex()
    if (idx >= ctx.hooks.length) {
      ctx.hooks[idx] = pyreonSignal<T>(initialValue)
    }
    const s = ctx.hooks[idx] as ReturnType<typeof pyreonSignal<T>>
    const { scheduleRerender } = ctx

    const getter: SignalGetter<T> = () => s()
    const setter: SignalSetter<T> = (v) => {
      if (typeof v === "function") {
        s.update(v as (prev: T) => T)
      } else {
        s.set(v)
      }
      scheduleRerender()
    }
    return [getter, setter]
  }

  // Outside component — plain Pyreon signal
  const s = pyreonSignal<T>(initialValue)
  const getter: SignalGetter<T> = () => s()
  const setter: SignalSetter<T> = (v) => {
    if (typeof v === "function") {
      s.update(v as (prev: T) => T)
    } else {
      s.set(v)
    }
  }
  return [getter, setter]
}

// ─── createEffect ────────────────────────────────────────────────────────────

/**
 * Solid-compatible `createEffect` — creates a reactive side effect.
 *
 * In component context: hook-indexed, only created on first render. The effect
 * uses Pyreon's native tracking so signal reads are automatically tracked.
 * A re-entrance guard prevents infinite loops from signal writes inside
 * the effect.
 */
export function createEffect(fn: () => void): void {
  const ctx = getCurrentCtx()
  if (ctx) {
    const idx = getHookIndex()
    if (idx < ctx.hooks.length) return // Already registered on first render

    let running = false
    const e = pyreonEffect(() => {
      if (running) return
      running = true
      try {
        fn()
      } finally {
        running = false
      }
    })
    const stop = () => e.dispose()
    ctx.hooks[idx] = stop
    ctx.unmountCallbacks.push(stop)
    return
  }

  // Outside component
  pyreonEffect(fn)
}

// ─── createRenderEffect ──────────────────────────────────────────────────────

/**
 * Solid-compatible `createRenderEffect` — same as createEffect.
 * In Solid, this runs during the render phase; here it runs as a Pyreon effect.
 */
export function createRenderEffect(fn: () => void): void {
  createEffect(fn)
}

// ─── createComputed (legacy Solid API) ───────────────────────────────────────

export { createEffect as createComputed }

// ─── createMemo ──────────────────────────────────────────────────────────────

/**
 * Solid-compatible `createMemo` — derives a value from reactive sources.
 *
 * In component context: hook-indexed, only created on first render.
 * Uses Pyreon's native computed for auto-tracking.
 */
export function createMemo<T>(fn: () => T): () => T {
  const ctx = getCurrentCtx()
  if (ctx) {
    const idx = getHookIndex()
    if (idx >= ctx.hooks.length) {
      ctx.hooks[idx] = pyreonComputed(fn)
    }
    const c = ctx.hooks[idx] as ReturnType<typeof pyreonComputed<T>>
    return () => c()
  }

  // Outside component
  const c = pyreonComputed(fn)
  return () => c()
}

// ─── createRoot ──────────────────────────────────────────────────────────────

export function createRoot<T>(fn: (dispose: () => void) => T): T {
  const scope = effectScope()
  const prev = getCurrentScope()
  setCurrentScope(scope)
  try {
    return fn(() => scope.stop())
  } finally {
    setCurrentScope(prev)
  }
}

// ─── on ──────────────────────────────────────────────────────────────────────

type AccessorArray = readonly (() => unknown)[]
type OnEffectFunction<D, V> = (input: D, prevInput: D | undefined, prev: V | undefined) => V

export function on<S extends (() => unknown) | AccessorArray, V>(
  deps: S,
  fn: OnEffectFunction<
    S extends () => infer R ? R : S extends readonly (() => infer R)[] ? R[] : never,
    V
  >,
): () => V | undefined {
  type D = S extends () => infer R ? R : S extends readonly (() => infer R)[] ? R[] : never

  let prevInput: D | undefined
  let prevValue: V | undefined
  let initialized = false

  return () => {
    // Read dependencies to register tracking
    const input: D = (
      Array.isArray(deps) ? (deps as (() => unknown)[]).map((d) => d()) : (deps as () => unknown)()
    ) as D

    if (!initialized) {
      initialized = true
      prevValue = fn(input, undefined, undefined)
      prevInput = input
      return prevValue
    }

    const result = runUntracked(() => fn(input, prevInput, prevValue))
    prevInput = input
    prevValue = result
    return result
  }
}

// ─── batch ───────────────────────────────────────────────────────────────────

export { pyreonBatch as batch }

// ─── untrack ─────────────────────────────────────────────────────────────────

export { runUntracked as untrack }

// ─── onMount / onCleanup ─────────────────────────────────────────────────────

/**
 * Solid-compatible `onMount` — runs once after the component's first render.
 */
type CleanupFn = () => void
export function onMount(fn: () => CleanupFn | undefined): void {
  const ctx = getCurrentCtx()
  if (ctx) {
    const idx = getHookIndex()
    if (idx >= ctx.hooks.length) {
      ctx.hooks[idx] = true
      ctx.pendingEffects.push({
        fn: () => {
          fn()
          return undefined
        },
        deps: undefined,
        cleanup: undefined,
      })
    }
    return
  }

  // Outside component
  pyreonOnMount(fn)
}

/**
 * Solid-compatible `onCleanup` — registers a callback to run when the component unmounts.
 */
export function onCleanup(fn: () => void): void {
  const ctx = getCurrentCtx()
  if (ctx) {
    const idx = getHookIndex()
    if (idx >= ctx.hooks.length) {
      ctx.hooks[idx] = true
      ctx.unmountCallbacks.push(fn)
    }
    return
  }

  // Outside component
  pyreonOnUnmount(fn)
}

// ─── createSelector ──────────────────────────────────────────────────────────

export function createSelector<T>(source: () => T): (key: T) => boolean {
  const ctx = getCurrentCtx()
  if (ctx) {
    const idx = getHookIndex()
    if (idx >= ctx.hooks.length) {
      ctx.hooks[idx] = pyreonCreateSelector(source)
    }
    return ctx.hooks[idx] as (key: T) => boolean
  }

  return pyreonCreateSelector(source)
}

// ─── mergeProps ──────────────────────────────────────────────────────────────

type UnionToIntersection<U> = (U extends unknown ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never

type MergeProps<T extends object[]> = UnionToIntersection<T[number]>

export function mergeProps<T extends object[]>(...sources: [...T]): MergeProps<T> {
  const target = {} as Record<PropertyKey, unknown>
  for (const source of sources) {
    const descriptors = Object.getOwnPropertyDescriptors(source)
    for (const key of Reflect.ownKeys(descriptors)) {
      const desc = descriptors[key as string]
      if (!desc) continue
      // Preserve getters for reactivity
      if (desc.get) {
        Object.defineProperty(target, key, {
          get: desc.get,
          enumerable: true,
          configurable: true,
        })
      } else {
        Object.defineProperty(target, key, {
          value: desc.value,
          writable: true,
          enumerable: true,
          configurable: true,
        })
      }
    }
  }
  return target as MergeProps<T>
}

// ─── splitProps ──────────────────────────────────────────────────────────────

export function splitProps<T extends Record<string, unknown>, K extends (keyof T)[]>(
  props: T,
  ...keys: K
): [Pick<T, K[number]>, Omit<T, K[number]>] {
  const picked = {} as Pick<T, K[number]>
  const rest = {} as Record<string, unknown>
  const keySet = new Set<string>(keys.flat() as string[])

  const descriptors = Object.getOwnPropertyDescriptors(props)
  for (const key of Reflect.ownKeys(descriptors)) {
    const desc = descriptors[key as string]
    if (!desc) continue
    const target = typeof key === "string" && keySet.has(key) ? picked : rest
    if (desc.get) {
      Object.defineProperty(target, key, {
        get: desc.get,
        enumerable: true,
        configurable: true,
      })
    } else {
      Object.defineProperty(target, key, {
        value: desc.value,
        writable: true,
        enumerable: true,
        configurable: true,
      })
    }
  }

  return [picked, rest as Omit<T, K[number]>]
}

// ─── children ────────────────────────────────────────────────────────────────

export function children(fn: () => VNodeChild): () => VNodeChild {
  const memo = createMemo(() => {
    const result = fn()
    // Resolve function children (reactive getters)
    if (typeof result === "function") return (result as () => VNodeChild)()
    return result
  })
  return memo
}

// ─── lazy ────────────────────────────────────────────────────────────────────

export function lazy<P extends Props>(
  loader: () => Promise<{ default: ComponentFn<P> }>,
): LazyComponent<P> & { preload: () => Promise<{ default: ComponentFn<P> }> } {
  const loaded = pyreonSignal<ComponentFn<P> | null>(null)
  const error = pyreonSignal<Error | null>(null)
  let promise: Promise<{ default: ComponentFn<P> }> | null = null

  const load = () => {
    if (!promise) {
      promise = loader()
        .then((mod) => {
          loaded.set(mod.default)
          return mod
        })
        .catch((err) => {
          const e = err instanceof Error ? err : new Error(String(err))
          error.set(e)
          promise = null
          throw e
        })
    }
    return promise
  }

  // Uses Pyreon's __loading protocol — Suspense checks this to show fallback.
  // __loading() triggers load() on first call so loading starts when Suspense
  // first encounters the component (not at module load time, not on first render).
  const LazyComponent = ((props: P) => {
    const err = error()
    if (err) throw err
    const comp = loaded()
    if (!comp) return null
    return comp(props)
  }) as LazyComponent<P> & { preload: () => Promise<{ default: ComponentFn<P> }> }

  LazyComponent.__loading = () => {
    const isLoading = loaded() === null && error() === null
    if (isLoading) load()
    return isLoading
  }
  LazyComponent.preload = load

  return LazyComponent
}

// ─── createContext / useContext ───────────────────────────────────────────────

export { pyreonCreateContext as createContext, pyreonUseContext as useContext }

// ─── getOwner / runWithOwner ─────────────────────────────────────────────────

export function getOwner(): EffectScope | null {
  return getCurrentScope()
}

export function runWithOwner<T>(owner: EffectScope | null, fn: () => T): T {
  const prev = getCurrentScope()
  setCurrentScope(owner)
  try {
    return fn()
  } finally {
    setCurrentScope(prev)
  }
}

// ─── Re-exports from @pyreon/core ──────────────────────────────────────────────

export { ErrorBoundary, For, Match, Show, Suspense, Switch }
