// examples/solid-compat/src/examples/ShowDemo.tsx
import { createSignal, Show } from "solid-js"
import Demo from "./Demo"

export default function ShowDemo() {
  const [visible, setVisible] = createSignal(true)

  return (
    <Demo
      title="Conditional Rendering"
      apis="Show"
      code={`const [visible, setVisible] = createSignal(true);

<Show
  when={visible}
  fallback={<p>Nothing to see here</p>}
>
  <p>Hello, I'm visible!</p>
</Show>`}
    >
      <button type="button" onClick={() => setVisible((v) => !v)}>
        Toggle ({visible() ? "visible" : "hidden"})
      </button>
      <Show when={visible} fallback={<p class="muted">Nothing to see here</p>}>
        <p>Hello, I'm visible!</p>
      </Show>
    </Demo>
  )
}

// examples/svelte-compat/src/examples/ShowDemo.tsx
import { Show, writable } from 'svelte'
import Demo from './Demo'

export default function ShowDemo() {
  const on = writable(true)
  let flag = true
  on.subscribe((v) => (flag = v))

  return (
    <Demo
      title="Show (control-flow re-export)"
      apis="Show"
      code={`<Show when={flag}>…</Show>`}
    >
      <Show when={flag} fallback={<p class="muted">hidden</p>}>
        <p class="highlight">visible ✓</p>
      </Show>
      <button type="button" onClick={() => on.update((v) => !v)}>
        toggle
      </button>
    </Demo>
  )
}
