// examples/react-compat/src/examples/ErrorDemo.tsx
import { ErrorBoundary, useState } from "react";
import Demo from "./Demo";

function Bomb(): JSX.Element {
  throw new Error("Boom!");
}

export default function ErrorDemo() {
  const [explode, setExplode] = useState(false);

  return (
    <Demo
      title="Error Handling"
      apis="ErrorBoundary"
      code={`<ErrorBoundary
  fallback={(err) => <p>Caught: {err.message}</p>}
>
  <RiskyComponent />
</ErrorBoundary>`}
    >
      <div class="row">
        <button type="button" onClick={() => setExplode(true)}>
          Trigger Error
        </button>
        <button type="button" onClick={() => setExplode(false)}>
          Reset
        </button>
      </div>
      <ErrorBoundary
        fallback={(err: unknown, _reset: () => void) => (
          <p class="error-msg">Caught: {(err as Error).message}</p>
        )}
      >
        {explode ? <Bomb /> : <p class="muted">No errors yet</p>}
      </ErrorBoundary>
    </Demo>
  );
}

// examples/solid-compat/src/examples/ErrorDemo.tsx
import { createSignal, ErrorBoundary, Show } from 'solid-js'
import Demo from './Demo'

function Bomb(): JSX.Element {
  throw new Error('Boom!')
}

export default function ErrorDemo() {
  const [explode, setExplode] = createSignal(false)

  return (
    <Demo
      title="Error Handling"
      apis="ErrorBoundary"
      code={`<ErrorBoundary
  fallback={(err) => <p>Caught: {err.message}</p>}
>
  <RiskyComponent />
</ErrorBoundary>`}
    >
      <button type="button" onClick={() => setExplode(true)}>
        Trigger Error
      </button>
      <button type="button" onClick={() => setExplode(false)}>
        Reset
      </button>
      <ErrorBoundary
        fallback={(err: unknown, _reset: () => void) => (
          <p class="error-msg">Caught: {(err as Error).message}</p>
        )}
      >
        <Show when={explode}>
          <Bomb />
        </Show>
        <Show when={() => !explode()}>
          <p class="muted">No errors yet — click to trigger</p>
        </Show>
      </ErrorBoundary>
    </Demo>
  )
}
